### ISSUE TITLE
Предложения по функционалу создания колоды

### ISSUE THREAD

**Issue by Veidimadr** [SkAZi/bersency-nxt-release#1]
Добрый день, спасибо за отличную программу, ниже несколько предложений по доработке, надеюсь, что-то из этого будет полезно и внедрено в последующие версии:
1. При просмотре карт в увеличенном виде через ПКМ добавить возможность перелистывать следующую/предыдущую карту по клавишам стрелок на клавиатуре.

**Comment by SkAZi** [comment]
Будет в следующей сборке
